version: '3.7'

services:

  db:
    image: mariadb
    container_name: mariadb
    restart: always
    ports:
        - "3306:3306"    
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    volumes:
      - ${MYSQL_DB_FILE:-/var/thisismyspace/db}:/var/lib/mysql
    networks:
      - ${APP_NETWORK:-thisismyspace}

  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt
    network_mode: host
    restart: always
    volumes:
      - ${MQTT_CONFIG:-/var/thisismyspace/mqtt/config}:/mosquitto/config
      - ${MQTT_DATA:-/var/thisismyspace/mqtt/data}:/mosquitto/data
      - ${MQTT_LOG:-/var/thisismyspace/mqtt/log}:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
  
  

networks:

  thisismyspace:
    #internal: true
    name: ${APP_NETWORK:-thisismyspace}
